language: python

python: "3.7"

before_install:
  mv ./config/secrets.travis.yaml ./config/secrets.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog

script:
  - hass -c ./config --script check_config --info all
