# Kitchen backlight
- id: kitchen_backlight
  alias: 'Kitchen backlight'
  hide_entity: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00018392c4
        click_type: single   
  action:
    - service: switch.toggle
      data:
        entity_id: switch.plug_158d00015c77a8

# Night light turn on
- id: night_light_turn_on
  alias: 'Night light turn on'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00015a9c49
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d00015a9c49
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.gateway_light_34ce0082a52d
      data:
        brightness_pct: 30
        color_name: 'orange'

# Night light turn off
- id: night_light_turn_off
  alias: 'Night light turn off'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00015a9c49
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d00015a9c49
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_34ce0082a52d    