media_player.bedroom_tv:
    friendly_name: 'Bedroom TV'
binary_sensor.switch_158d00018392c4:
    friendly_name: 'Kitchen backlight switch'
switch.plug_158d00015c77a8:
    friendly_name: 'Kichen backlight'
sensor.temperature_158d00019cf3f2:
    friendly_name: 'Bedroom temperature'
sensor.humidity_158d00019cf3f2:
    friendly_name: 'Bedroom humidity'
sensor.owm_humidity:
    friendly_name: 'Outdoor humidity'
light.gateway_light_34ce0082a52d:
    friendly_name: 'Gateway backlight'