home_name: Home Name
home_latitude: 000.0000000
home_longitude: 000.0000000
xiaomi_gateway_token: ABCDEF0123456789
bedroom_tv_host: 192.168.0.1
bedroom_tv_mac: 00:00:00:00:00
bedroom_appletv_host: 192.168.0.1
bedroom_appletv_login_id: 00000000-1234-5678-9012-345678901234
bedroom_appletv_credentials: 1B8C387DDB59BDF6:CF5ABB6A2C070688F5926ADB7C010F6DF847252C15F9BDB6DA3E09D6591E90E5