name: Validate HASS config
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate HASS config
      users: docker://homeassistant/home-assistant:0.97.2
      run: |
        mv ./config/secrets.travis.yaml ./config/secrets.yaml
        python -m homeassistant --config config --script check_config --info all
